services:
  - type: web
    name: derma-api
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
